"""add client_app, api_key, service, scope, request_log, observation_analysis tables

Revision ID: 2eb3b414523a
Revises: 1a3d1a7a5663
Create Date: 2026-07-15 21:47:45.058333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2eb3b414523a'
down_revision: Union[str, None] = '1a3d1a7a5663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_service_key'), 'services', ['service_key'], unique=True)
    op.create_table('client_apps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_apps_client_id'), 'client_apps', ['client_id'], unique=True)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_app_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=12), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_app_id'], ['client_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_request_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_app_id', sa.UUID(), nullable=True),
    sa.Column('service_key', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_app_id'], ['client_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_service_scopes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_app_id', sa.UUID(), nullable=False),
    sa.Column('service_key', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_app_id'], ['client_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_app_id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.String(length=64), nullable=False),
    sa.Column('subject_type', sa.String(length=100), nullable=False),
    sa.Column('subject_label', sa.String(length=255), nullable=False),
    sa.Column('total_observations', sa.Integer(), nullable=False),
    sa.Column('computed_confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('prediction', sa.String(length=2000), nullable=False),
    sa.Column('pattern_table_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_metrics_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_app_id'], ['client_apps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observation_analyses_analysis_id'), 'observation_analyses', ['analysis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observation_analyses_analysis_id'), table_name='observation_analyses')
    op.drop_table('observation_analyses')
    op.drop_table('client_service_scopes')
    op.drop_table('api_request_logs')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_client_apps_client_id'), table_name='client_apps')
    op.drop_table('client_apps')
    op.drop_index(op.f('ix_services_service_key'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
